"""
Trading Models

Database models for trades, positions, and trade plans.
"""

from sqlalchemy import Column, String, Numeric, BigInteger, DateTime, Boolean, Enum, ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

from app.db.database import Base


class TradeStatus(str, enum.Enum):
    """Trade status enumeration."""
    PLANNED = "planned"
    PENDING = "pending"
    OPEN = "open"
    PARTIAL = "partial"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class TradeDirection(str, enum.Enum):
    """Trade direction enumeration."""
    LONG = "long"
    SHORT = "short"


class ExitType(str, enum.Enum):
    """Exit type enumeration."""
    STOP_LOSS = "stop_loss"
    TARGET_1 = "target_1"
    TARGET_2 = "target_2"
    TRAILING_STOP = "trailing_stop"
    TIME_STOP = "time_stop"
    MANUAL = "manual"


class TradePlan(Base):
    """
    Trade plan generated by the Risk Management Engine.
    
    Contains the complete trade structure before execution.
    """
    __tablename__ = "trade_plans"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    symbol = Column(String(50), nullable=False, index=True)
    
    # Plan status
    status = Column(String(20), default="pending")  # pending, approved, rejected, executed
    
    # Entry parameters
    entry_price = Column(Numeric(12, 2), nullable=False)
    entry_zone_lower = Column(Numeric(12, 2), nullable=True)
    entry_zone_upper = Column(Numeric(12, 2), nullable=True)
    
    # Risk parameters
    stop_loss = Column(Numeric(12, 2), nullable=False)
    target_1 = Column(Numeric(12, 2), nullable=False)
    target_2 = Column(Numeric(12, 2), nullable=True)
    
    # Position sizing
    position_size = Column(BigInteger, nullable=False)
    capital_required = Column(Numeric(14, 2), nullable=False)
    risk_amount = Column(Numeric(12, 2), nullable=False)
    risk_percent = Column(Numeric(5, 2), nullable=False)
    
    # Predictions
    expected_return = Column(Numeric(8, 4), nullable=False)
    probability_win = Column(Numeric(5, 4), nullable=False)
    confidence_score = Column(Numeric(5, 4), nullable=False)
    rr_ratio_t1 = Column(Numeric(6, 2), nullable=False)
    rr_ratio_t2 = Column(Numeric(6, 2), nullable=True)
    
    # Context
    regime = Column(String(50), nullable=True)
    technical_score = Column(Numeric(4, 1), nullable=True)
    rationale = Column(JSONB, nullable=True)  # List of signal explanations
    
    # Prediction details
    return_10th_percentile = Column(Numeric(8, 4), nullable=True)
    return_50th_percentile = Column(Numeric(8, 4), nullable=True)
    return_90th_percentile = Column(Numeric(8, 4), nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    
    # Relationships
    trades = relationship("Trade", back_populates="plan")


class Trade(Base):
    """
    Executed trade record.
    
    Tracks actual fills vs planned, slippage, and outcomes.
    """
    __tablename__ = "trades"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    plan_id = Column(BigInteger, ForeignKey("trade_plans.id"), nullable=True)
    symbol = Column(String(50), nullable=False, index=True)
    
    # Trade details
    direction = Column(String(10), default="long")  # long, short
    status = Column(String(20), default="open")  # open, closed, cancelled
    
    # Entry
    planned_entry = Column(Numeric(12, 2), nullable=True)
    actual_entry = Column(Numeric(12, 2), nullable=False)
    entry_slippage_pct = Column(Numeric(6, 4), nullable=True)
    entry_time = Column(DateTime, nullable=False)
    entry_order_type = Column(String(20), nullable=True)  # market, limit
    
    # Position
    planned_quantity = Column(BigInteger, nullable=True)
    actual_quantity = Column(BigInteger, nullable=False)
    remaining_quantity = Column(BigInteger, nullable=True)
    
    # Exit
    exit_price = Column(Numeric(12, 2), nullable=True)
    exit_slippage_pct = Column(Numeric(6, 4), nullable=True)
    exit_time = Column(DateTime, nullable=True)
    exit_type = Column(String(20), nullable=True)  # stop_loss, target_1, target_2, manual
    
    # Risk levels (may be updated during trade)
    stop_loss = Column(Numeric(12, 2), nullable=True)
    target_1 = Column(Numeric(12, 2), nullable=True)
    target_2 = Column(Numeric(12, 2), nullable=True)
    
    # P&L
    gross_pnl = Column(Numeric(14, 2), nullable=True)
    total_charges = Column(Numeric(10, 2), nullable=True)  # Brokerage + taxes
    net_pnl = Column(Numeric(14, 2), nullable=True)
    return_pct = Column(Numeric(8, 4), nullable=True)
    
    # Duration
    days_held = Column(BigInteger, nullable=True)
    
    # Behavioral tracking
    deviations = Column(JSONB, nullable=True)  # List of plan deviations
    emotion_tag = Column(String(20), nullable=True)  # FOMO, FEAR, HOPE, DISCIPLINED
    
    # Context
    regime_at_entry = Column(String(50), nullable=True)
    regime_at_exit = Column(String(50), nullable=True)
    
    # Notes
    notes = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    plan = relationship("TradePlan", back_populates="trades")


class Position(Base):
    """
    Open position tracking.
    
    Real-time position monitoring with P&L updates.
    """
    __tablename__ = "positions"

    id = Column(BigInteger, primary_key=True, autoincrement=True)
    trade_id = Column(BigInteger, ForeignKey("trades.id"), nullable=False)
    symbol = Column(String(50), nullable=False, index=True)
    
    # Position details
    direction = Column(String(10), default="long")
    quantity = Column(BigInteger, nullable=False)
    avg_entry_price = Column(Numeric(12, 2), nullable=False)
    
    # Current state
    current_price = Column(Numeric(12, 2), nullable=True)
    unrealized_pnl = Column(Numeric(14, 2), nullable=True)
    unrealized_pnl_pct = Column(Numeric(8, 4), nullable=True)
    
    # Risk levels
    stop_loss = Column(Numeric(12, 2), nullable=False)
    target_1 = Column(Numeric(12, 2), nullable=False)
    target_2 = Column(Numeric(12, 2), nullable=True)
    capital_at_risk = Column(Numeric(14, 2), nullable=False)
    
    # Progress
    progress_to_target = Column(Numeric(5, 2), nullable=True)  # Percentage
    progress_to_stop = Column(Numeric(5, 2), nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True)
    days_held = Column(BigInteger, default=0)
    entry_date = Column(DateTime, nullable=False)
    
    # Alerts
    alerts_sent = Column(JSONB, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
